import os, io, base64, json
from PIL import Image

def get_blur(p):
    with Image.open(p) as img:
        img = img.convert('RGB')
        img.thumbnail((16, 16))
        buf = io.BytesIO()
        img.save(buf, format='JPEG', quality=60)
        return 'data:image/jpeg;base64,' + base64.b64encode(buf.getvalue()).decode('utf-8')

def get_wh(p):
    with Image.open(p) as img:
        return img.width, img.height

images_meta = [
  {
    'id': 'haske-official-portrait-1920',
    'src': '/images/abdulrahman/portraits/abdulrahman-haske-official-portrait.jpg',
    'disk': 'public/images/abdulrahman/portraits/abdulrahman-haske-official-portrait.jpg',
    'alt': 'Abdulrahman Bashir Haske official executive portrait',
    'title': 'Official Executive Portrait',
    'caption': 'Abdulrahman Bashir Haske, Nigerian entrepreneur, philanthropist, and public leadership figure.',
    'category': 'portraits',
    'date': '2026',
    'location': 'Yola, Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: Wikimedia Commons / Abdulrahman Haske (CC0)',
    'source': 'Wikimedia Commons',
    'sourceUrl': 'https://commons.wikimedia.org/wiki/File:Abdulrahman_Bashir_Haske.jpg',
    'license': 'Creative Commons CC0 1.0 Universal (Public Domain)',
    'licenseUrl': 'https://creativecommons.org/publicdomain/zero/1.0/',
    'status': 'OFFICIAL',
    'verified': True,
    'ogCandidate': True,
  },
  {
    'id': 'haske-formal-traditional',
    'src': '/images/abdulrahman/portraits/abdulrahman-haske-formal-traditional.jpg',
    'disk': 'public/images/abdulrahman/portraits/abdulrahman-haske-formal-traditional.jpg',
    'alt': 'Abdulrahman Bashir Haske in formal traditional attire',
    'title': 'Formal Traditional Portrait',
    'caption': 'Abdulrahman Bashir Haske in ceremonial Northern attire.',
    'category': 'portraits',
    'date': '2026',
    'location': 'Adamawa State',
    'subjectConfirmed': True,
    'photographer': 'ElsieIReed',
    'credit': 'Photo: ElsieIReed via Wikimedia Commons (CC BY 4.0)',
    'source': 'Wikimedia Commons',
    'sourceUrl': 'https://commons.wikimedia.org/wiki/File:IMG-20260215-WA0004(1).jpg',
    'license': 'Creative Commons Attribution 4.0 International (CC BY 4.0)',
    'licenseUrl': 'https://creativecommons.org/licenses/by/4.0/',
    'status': 'LICENSED',
    'verified': True,
  },
  {
    'id': 'haske-executive-editorial',
    'src': '/images/abdulrahman/portraits/abdulrahman-haske-executive-editorial.webp',
    'disk': 'public/images/abdulrahman/portraits/abdulrahman-haske-executive-editorial.webp',
    'alt': 'Abdulrahman Bashir Haske editorial executive profile',
    'title': 'Executive Profile Portrait',
    'caption': 'Abdulrahman Bashir Haske profiled for leadership, industrial enterprise, and humanitarian initiatives.',
    'category': 'portraits',
    'date': '2026',
    'location': 'Nigeria',
    'subjectConfirmed': True,
    'credit': 'Photo: The Gazette Nigeria',
    'source': 'The Gazette Nigeria',
    'sourceUrl': 'https://thegazette.ng/abdulrahman-haske-african-humanitarian-award/',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },
  {
    'id': 'haske-leadership-portrait',
    'src': '/images/abdulrahman/portraits/abdulrahman-haske-leadership-portrait.jpg',
    'disk': 'public/images/abdulrahman/portraits/abdulrahman-haske-leadership-portrait.jpg',
    'alt': 'Abdulrahman Bashir Haske candidacy declaration portrait',
    'title': '2027 Declaration Portrait',
    'caption': 'Official leadership portrait published during his 2027 gubernatorial declaration.',
    'category': 'portraits',
    'date': '2026-04',
    'location': 'Yola, Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: Leadership Newspaper',
    'source': 'Leadership Newspaper',
    'sourceUrl': 'https://leadership.ng/momentum-builds-as-abdulrahman-haske-declares-for-2027-adamawa-governorship-race/',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },
  {
    'id': 'haske-ceremonial-profile',
    'src': '/images/abdulrahman/portraits/abdulrahman-haske-ceremonial-profile.jpg',
    'disk': 'public/images/abdulrahman/portraits/abdulrahman-haske-ceremonial-profile.jpg',
    'alt': 'Abdulrahman Bashir Haske ceremonial portrait',
    'title': 'Ceremonial Executive Profile',
    'caption': 'Abdulrahman Bashir Haske featured in national political analysis.',
    'category': 'portraits',
    'date': '2026-03',
    'location': 'Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: THISDAY Live',
    'source': 'THISDAY Live',
    'sourceUrl': 'https://www.thisdaylive.com/2026/03/28/abdulrahman-bashir-haske-is-the-top-man-on-the-block-in-the-2027-adamawa-state-politics/',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },
  {
    'id': 'haske-apm-announcement',
    'src': '/images/abdulrahman/portraits/abdulrahman-haske-apm-announcement.jpg',
    'disk': 'public/images/abdulrahman/portraits/abdulrahman-haske-apm-announcement.jpg',
    'alt': 'Abdulrahman Bashir Haske APM candidacy announcement portrait',
    'title': 'APM Gubernatorial Candidacy',
    'caption': 'Abdulrahman Bashir Haske emerges as governorship candidate for the Allied Peoples Movement (APM).',
    'category': 'portraits',
    'date': '2026-09',
    'location': 'Yola, Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: The Whistler Newspaper',
    'source': 'The Whistler Newspaper',
    'sourceUrl': 'https://thewhistler.ng/major-upset-in-adamawa-politics-as-haske-emerges-apm-guber-candidate/',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },
  {
    'id': 'haske-speaking-portrait',
    'src': '/images/abdulrahman/portraits/abdulrahman-haske-speaking-portrait.jpeg',
    'disk': 'public/images/abdulrahman/portraits/abdulrahman-haske-speaking-portrait.jpeg',
    'alt': 'Abdulrahman Bashir Haske addressing public gathering',
    'title': 'Public Address Portrait',
    'caption': 'Abdulrahman Bashir Haske delivering his address during public engagement in Yola.',
    'category': 'portraits',
    'date': '2026-04',
    'location': 'Yola, Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: Premium Times',
    'source': 'Premium Times',
    'sourceUrl': 'https://www.premiumtimesng.com/promoted/874756-yola-agog-as-abdulrahman-haske-finally-declares-for-adamawa-governorship-race.html',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },

  # Business
  {
    'id': 'business-enterprise-leadership',
    'src': '/images/abdulrahman/business/haske-executive-enterprise-leadership.jpg',
    'disk': 'public/images/abdulrahman/business/haske-executive-enterprise-leadership.jpg',
    'alt': 'Abdulrahman Bashir Haske corporate leadership',
    'title': 'Executive Enterprise Leadership',
    'caption': 'Corporate governance and executive leadership across diversified sectors in Northern Nigeria.',
    'category': 'business',
    'date': '2026',
    'location': 'Nigeria',
    'subjectConfirmed': True,
    'credit': 'Photo: THISDAY Live',
    'source': 'THISDAY Live',
    'sourceUrl': 'https://www.thisdaylive.com/2026/03/28/abdulrahman-bashir-haske-is-the-top-man-on-the-block-in-the-2027-adamawa-state-politics/',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },
  {
    'id': 'business-hw-industrial-plant',
    'src': '/images/abdulrahman/business/hw-industrial-processing-plant.jpg',
    'disk': 'public/images/abdulrahman/business/hw-industrial-processing-plant.jpg',
    'alt': 'Industrial agro-processing plant operations in Adamawa',
    'title': 'Industrial Plant Operations',
    'caption': 'Modern mechanized agro-processing operations associated with Haske & Williams Company.',
    'category': 'business',
    'date': 'Operational archive',
    'location': 'Demsa LGA, Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: H&W Rice Company Ltd',
    'source': 'H&W Rice Company',
    'sourceUrl': 'https://hwriceco.com',
    'license': 'Corporate project archive',
    'status': 'OFFICIAL',
    'verified': True,
  },
  {
    'id': 'business-hw-agro-complex',
    'src': '/images/abdulrahman/business/hw-agro-industrial-complex.jpg',
    'disk': 'public/images/abdulrahman/business/hw-agro-industrial-complex.jpg',
    'alt': 'Agro-industrial milling complex in Adamawa State',
    'title': 'Agro-Industrial Milling Complex',
    'caption': 'The 48-ton/day integrated milling infrastructure developed in Demsa, Adamawa State.',
    'category': 'business',
    'date': 'Operational archive',
    'location': 'Demsa LGA, Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: H&W Rice Company Ltd',
    'source': 'H&W Rice Company',
    'sourceUrl': 'https://hwriceco.com',
    'license': 'Corporate project archive',
    'status': 'OFFICIAL',
    'verified': True,
  },

  # Agriculture
  {
    'id': 'agriculture-mill-facility-demsa',
    'src': '/images/abdulrahman/agriculture/hw-rice-mill-facility-demsa.jpg',
    'disk': 'public/images/abdulrahman/agriculture/hw-rice-mill-facility-demsa.jpg',
    'alt': 'H&W Rice Company industrial facility in Demsa',
    'title': 'H&W Rice Processing Facility',
    'caption': 'Exterior view of the integrated industrial rice milling complex in Demsa, Adamawa State.',
    'category': 'agriculture',
    'date': 'Operational archive',
    'location': 'Demsa LGA, Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: H&W Rice Company Ltd',
    'source': 'H&W Rice Company',
    'sourceUrl': 'https://hwriceco.com',
    'license': 'Corporate project archive',
    'status': 'OFFICIAL',
    'verified': True,
  },
  {
    'id': 'agriculture-destoning-sorting',
    'src': '/images/abdulrahman/agriculture/hw-rice-destoning-sorting-line.jpg',
    'disk': 'public/images/abdulrahman/agriculture/hw-rice-destoning-sorting-line.jpg',
    'alt': 'Automated destoning and optical sorting line',
    'title': 'Automated Processing Line',
    'caption': 'Optical color sorting and destoning machinery meeting global rice milling standards.',
    'category': 'agriculture',
    'date': 'Operational archive',
    'location': 'Demsa Hub, Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: H&W Rice Company Ltd',
    'source': 'H&W Rice Company',
    'sourceUrl': 'https://hwriceco.com',
    'license': 'Corporate project archive',
    'status': 'OFFICIAL',
    'verified': True,
  },
  {
    'id': 'agriculture-milling-machinery',
    'src': '/images/abdulrahman/agriculture/hw-rice-milling-machinery.jpg',
    'disk': 'public/images/abdulrahman/agriculture/hw-rice-milling-machinery.jpg',
    'alt': 'Pneumatic milling and processing machinery at Demsa facility',
    'title': 'Advanced Milling Machinery',
    'caption': 'Pneumatic rice flour and bran processing equipment installed at the Demsa facility.',
    'category': 'agriculture',
    'date': 'Operational archive',
    'location': 'Demsa Hub, Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: H&W Rice Company Ltd',
    'source': 'H&W Rice Company',
    'sourceUrl': 'https://hwriceco.com',
    'license': 'Corporate project archive',
    'status': 'OFFICIAL',
    'verified': True,
  },
  {
    'id': 'agriculture-packaged-parboiled',
    'src': '/images/abdulrahman/agriculture/hw-rice-packaged-parboiled.jpg',
    'disk': 'public/images/abdulrahman/agriculture/hw-rice-packaged-parboiled.jpg',
    'alt': 'H&W parboiled long-grain rice product packaging',
    'title': 'Premium Long-Grain Rice',
    'caption': 'High-grade domestic parboiled rice produced to replace imported grains across Nigerian markets.',
    'category': 'agriculture',
    'location': 'Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: H&W Rice Company Ltd',
    'source': 'H&W Rice Company',
    'sourceUrl': 'https://hwriceco.com',
    'license': 'Corporate project archive',
    'status': 'OFFICIAL',
    'verified': True,
  },
  {
    'id': 'agriculture-bran-valorization',
    'src': '/images/abdulrahman/agriculture/hw-rice-bran-valorization.jpg',
    'disk': 'public/images/abdulrahman/agriculture/hw-rice-bran-valorization.jpg',
    'alt': 'Rice bran byproduct processing',
    'title': 'Byproduct Valorization',
    'caption': 'Extracting rice bran value and utilizing husks for sustainable biomass energy.',
    'category': 'agriculture',
    'location': 'Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: H&W Rice Company Ltd',
    'source': 'H&W Rice Company',
    'sourceUrl': 'https://hwriceco.com',
    'license': 'Corporate project archive',
    'status': 'OFFICIAL',
    'verified': True,
  },

  # Foundation & Humanitarian
  {
    'id': 'foundation-ramadan-relief-grains',
    'src': '/images/abdulrahman/foundation/ab-haske-foundation-ramadan-relief.png',
    'disk': 'public/images/abdulrahman/foundation/ab-haske-foundation-ramadan-relief.png',
    'alt': 'AB Haske Foundation Ramadan grain distribution across Adamawa',
    'title': 'Annual Ramadan Food Distribution',
    'caption': 'AB Haske Foundation distribution of thousands of bags of rice and sugar across all 21 LGAs of Adamawa State.',
    'category': 'foundation',
    'date': '2026-02',
    'location': 'Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: Pioneer News / AB Haske Foundation',
    'source': 'Pioneer News',
    'sourceUrl': 'https://pioneernew.com/2026/02/21/ramadan-of-responsibility-haske-feeds-adamawa-shows-capacity-ahead-of-2027/',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },
  {
    'id': 'humanitarian-palliative-distribution',
    'src': '/images/abdulrahman/foundation/ab-haske-foundation-food-distribution.png',
    'disk': 'public/images/abdulrahman/foundation/ab-haske-foundation-food-distribution.png',
    'alt': 'Relief food distribution bags prepared by AB Haske Foundation',
    'title': 'Humanitarian Relief Operations',
    'caption': 'Vulnerable-household food aid and community welfare interventions championed by the AB Haske Foundation.',
    'category': 'humanitarian',
    'date': '2026',
    'location': 'Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: Pioneer News / AB Haske Foundation',
    'source': 'Pioneer News',
    'sourceUrl': 'https://pioneernew.com/2026/02/21/ramadan-of-responsibility-haske-feeds-adamawa-shows-capacity-ahead-of-2027/',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },

  # Youth & Education
  {
    'id': 'youth-mentorship-initiatives',
    'src': '/images/abdulrahman/youth/haske-youth-mentorship-initiatives.webp',
    'disk': 'public/images/abdulrahman/youth/haske-youth-mentorship-initiatives.webp',
    'alt': 'Abdulrahman Bashir Haske youth mentorship programs',
    'title': 'Youth & Education Empowerment',
    'caption': 'Mentoring tertiary students, supporting vocational education, and championing young innovators.',
    'category': 'youth-education',
    'date': '2026',
    'location': 'Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: The Gazette Nigeria / AB Haske Foundation',
    'source': 'The Gazette Nigeria',
    'sourceUrl': 'https://thegazette.ng/abdulrahman-haske-african-humanitarian-award/',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },

  # Politics & Leadership
  {
    'id': 'politics-declaration-podium',
    'src': '/images/abdulrahman/politics/haske-declaration-podium-yola.jpeg',
    'disk': 'public/images/abdulrahman/politics/haske-declaration-podium-yola.jpeg',
    'alt': 'Abdulrahman Bashir Haske addressing declaration rally from podium',
    'title': 'Ribadu Square Declaration Address',
    'caption': 'Abdulrahman Bashir Haske addressing citizens from the podium at Mahmud Ribadu Square, Yola.',
    'category': 'politics',
    'date': '2026-04-25',
    'location': 'Mahmud Ribadu Square, Yola, Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: Premium Times',
    'source': 'Premium Times',
    'sourceUrl': 'https://www.premiumtimesng.com/promoted/874756-yola-agog-as-abdulrahman-haske-finally-declares-for-adamawa-governorship-race.html',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },
  {
    'id': 'politics-declaration-stage-dignitaries',
    'src': '/images/abdulrahman/politics/haske-declaration-stage-dignitaries.jpeg',
    'disk': 'public/images/abdulrahman/politics/haske-declaration-stage-dignitaries.jpeg',
    'alt': 'Party dignitaries and community stakeholders on stage in Yola',
    'title': 'Declaration Stage Stakeholders',
    'caption': 'Party leaders and community representatives on stage during the declaration rally in Yola.',
    'category': 'politics',
    'date': '2026-04-25',
    'location': 'Mahmud Ribadu Square, Yola, Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: Premium Times',
    'source': 'Premium Times',
    'sourceUrl': 'https://www.premiumtimesng.com/promoted/874756-yola-agog-as-abdulrahman-haske-finally-declares-for-adamawa-governorship-race.html',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },
  {
    'id': 'leadership-ribadu-square-crowd',
    'src': '/images/abdulrahman/politics/haske-declaration-ribadu-square-crowd.jpeg',
    'disk': 'public/images/abdulrahman/politics/haske-declaration-ribadu-square-crowd.jpeg',
    'alt': 'Citizens gathered at Mahmud Ribadu Square in Yola',
    'title': 'Ribadu Square Civic Gathering',
    'caption': 'Supporters and citizens assembled at Mahmud Ribadu Square in Yola.',
    'category': 'leadership',
    'date': '2026-04-25',
    'location': 'Mahmud Ribadu Square, Yola, Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: Premium Times',
    'source': 'Premium Times',
    'sourceUrl': 'https://www.premiumtimesng.com/promoted/874756-yola-agog-as-abdulrahman-haske-finally-declares-for-adamawa-governorship-race.html',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },
  {
    'id': 'leadership-grassroots-consultation',
    'src': '/images/abdulrahman/politics/haske-grassroots-leadership-dialogue.jpg',
    'disk': 'public/images/abdulrahman/politics/haske-grassroots-leadership-dialogue.jpg',
    'alt': 'Abdulrahman Bashir Haske during community dialogue',
    'title': 'Grassroots Community Consultation',
    'caption': 'Abdulrahman Bashir Haske conducting grassroots civic dialogues across Adamawa communities.',
    'category': 'leadership',
    'date': '2026-08',
    'location': 'Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: The Nation Newspaper',
    'source': 'The Nation Newspaper',
    'sourceUrl': 'https://thenationonlineng.net/haske-and-the-push-for-productive-leadership-in-adamawa/',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },
  {
    'id': 'politics-vanguard-campaign',
    'src': '/images/abdulrahman/politics/haske-vanguard-guber-campaign.jpeg',
    'disk': 'public/images/abdulrahman/politics/haske-vanguard-guber-campaign.jpeg',
    'alt': 'Abdulrahman Haske candidacy announcement',
    'title': 'Vanguard Campaign Feature',
    'caption': 'Public policy roadmap and governance blueprint for Adamawa State.',
    'category': 'politics',
    'date': '2026-03',
    'location': 'Yola, Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: Vanguard News',
    'source': 'Vanguard News',
    'sourceUrl': 'https://www.vanguardngr.com/2026/03/abdulrahman-haske-eyes-2027-adamawa-governorship/',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },

  # Polo & Sports
  {
    'id': 'polo-yola-tournament-matchplay',
    'src': '/images/abdulrahman/polo/yola-polo-tournament-matchplay.webp',
    'disk': 'public/images/abdulrahman/polo/yola-polo-tournament-matchplay.webp',
    'alt': 'Matchplay at Lamido Musdafa Polo Ground in Yola',
    'title': 'Yola International Polo Tournament',
    'caption': 'High-goal tournament action at Lamido Musdafa Polo Ground, presided over by Yola Polo Club President Abdulrahman Bashir Haske.',
    'category': 'polo',
    'date': '2026-08',
    'location': 'Lamido Musdafa Polo Ground, Yola, Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: The Nation Newspaper / Headtopics',
    'source': 'The Nation Newspaper',
    'sourceUrl': 'https://thenationonlineng.net/haske-pledges-exciting-2026-yola-international-polo-tournament/',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },
  {
    'id': 'polo-club-patron-haske',
    'src': '/images/abdulrahman/polo/yola-polo-club-patron-haske.jpg',
    'disk': 'public/images/abdulrahman/polo/yola-polo-club-patron-haske.jpg',
    'alt': 'Yola Polo Club President Abdulrahman Bashir Haske',
    'title': 'Yola Polo Club Leadership',
    'caption': 'Abdulrahman Bashir Haske, President of the Yola Polo Club and patron of the Haske & Williams Polo Team.',
    'category': 'polo',
    'date': '2026-08',
    'location': 'Yola, Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: The Nation Newspaper',
    'source': 'The Nation Newspaper',
    'sourceUrl': 'https://thenationonlineng.net/haske-pledges-exciting-2026-yola-international-polo-tournament/',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },

  # Awards
  {
    'id': 'awards-aha-receiving',
    'src': '/images/abdulrahman/awards/aha-ghana-haske-receiving-award.jpg',
    'disk': 'public/images/abdulrahman/awards/aha-ghana-haske-receiving-award.jpg',
    'alt': 'Abdulrahman Bashir Haske receiving African Humanitarian Award in Ghana',
    'title': 'African Humanitarian Award Presentation',
    'caption': 'Abdulrahman Bashir Haske receiving the Distinguished African Humanitarian Award at the African Heritage Awards in Accra, Ghana.',
    'category': 'awards',
    'date': '2026-04-11',
    'location': 'Accra, Ghana',
    'subjectConfirmed': True,
    'credit': 'Photo: BusinessDay Nigeria',
    'source': 'BusinessDay Nigeria',
    'sourceUrl': 'https://businessday.ng/life/article/abdulrahman-haske-adesina-walson-jack-others-bag-african-heritage-awards/',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },
  {
    'id': 'awards-aha-honorees',
    'src': '/images/abdulrahman/awards/aha-ghana-honorees-group.jpg',
    'disk': 'public/images/abdulrahman/awards/aha-ghana-honorees-group.jpg',
    'alt': 'Honorees at the African Heritage Awards in Ghana',
    'title': 'African Heritage Awards Honorees',
    'caption': 'Continental honorees and dignitaries at the African Heritage Awards ceremony in Accra, Ghana.',
    'category': 'awards',
    'date': '2026-04-11',
    'location': 'Accra, Ghana',
    'subjectConfirmed': True,
    'credit': 'Photo: BusinessDay Nigeria',
    'source': 'BusinessDay Nigeria',
    'sourceUrl': 'https://businessday.ng/life/article/abdulrahman-haske-adesina-walson-jack-others-bag-african-heritage-awards/',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },
  {
    'id': 'awards-aha-delegation',
    'src': '/images/abdulrahman/awards/aha-ghana-nigerian-delegation.jpeg',
    'disk': 'public/images/abdulrahman/awards/aha-ghana-nigerian-delegation.jpeg',
    'alt': 'Nigerian delegation at African Heritage Awards in Accra',
    'title': 'Accra Continental Gala Delegation',
    'caption': 'Abdulrahman Bashir Haske alongside fellow award recipients at the 2026 African Heritage Awards in Accra.',
    'category': 'awards',
    'date': '2026-04-11',
    'location': 'Accra, Ghana',
    'subjectConfirmed': True,
    'credit': 'Photo: Premium Times',
    'source': 'Premium Times',
    'sourceUrl': 'https://www.premiumtimesng.com/promoted/871209-abdulrahman-haske-adesina-walson-jack-others-bag-african-heritage-awards.html',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },
  {
    'id': 'awards-aha-trophy-presentation',
    'src': '/images/abdulrahman/awards/aha-ghana-trophy-presentation.jpeg',
    'disk': 'public/images/abdulrahman/awards/aha-ghana-trophy-presentation.jpeg',
    'alt': 'Presentation of African Humanitarian Award trophy to Haske',
    'title': 'Humanitarian Recognition Ceremony',
    'caption': 'Trophy presentation honoring interventions in education, youth empowerment, and rural community health through the AB Haske Foundation.',
    'category': 'awards',
    'date': '2026-04-11',
    'location': 'Accra, Ghana',
    'subjectConfirmed': True,
    'credit': 'Photo: Premium Times',
    'source': 'Premium Times',
    'sourceUrl': 'https://www.premiumtimesng.com/promoted/871209-abdulrahman-haske-adesina-walson-jack-others-bag-african-heritage-awards.html',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },

  # International
  {
    'id': 'international-aha-summit-stage',
    'src': '/images/abdulrahman/international/aha-accra-international-summit-stage.jpg',
    'disk': 'public/images/abdulrahman/international/aha-accra-international-summit-stage.jpg',
    'alt': 'African Heritage Awards international summit stage in Accra',
    'title': 'African Heritage Awards Stage, Accra',
    'caption': 'The international summit stage in Accra, Ghana, celebrating pan-African leaders in governance, humanitarian service, and industry.',
    'category': 'international',
    'date': '2026-04-11',
    'location': 'Accra, Ghana',
    'subjectConfirmed': True,
    'credit': 'Photo: Streamline Feed / African Heritage Awards',
    'source': 'Streamline Feed',
    'sourceUrl': 'https://streamlinefeed.co.ke/news/african-heritage-awards-honor-adesina-haske-leaders-of-change',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },
  {
    'id': 'international-aha-presentation',
    'src': '/images/abdulrahman/international/aha-accra-humanitarian-award-presentation.jpg',
    'disk': 'public/images/abdulrahman/international/aha-accra-humanitarian-award-presentation.jpg',
    'alt': 'Abdulrahman Bashir Haske at international awards in Accra',
    'title': 'Pan-African Humanitarian Recognition',
    'caption': 'International recognition for social investment and grassroots empowerment in Accra, Ghana.',
    'category': 'international',
    'date': '2026-04-11',
    'location': 'Accra, Ghana',
    'subjectConfirmed': True,
    'credit': 'Photo: BusinessDay Nigeria',
    'source': 'BusinessDay Nigeria',
    'sourceUrl': 'https://businessday.ng/life/article/abdulrahman-haske-adesina-walson-jack-others-bag-african-heritage-awards/',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },
  {
    'id': 'international-pan-african-delegation',
    'src': '/images/abdulrahman/international/aha-accra-pan-african-delegation.jpeg',
    'disk': 'public/images/abdulrahman/international/aha-accra-pan-african-delegation.jpeg',
    'alt': 'Delegates and recipients at African Heritage Awards in Accra',
    'title': 'Pan-African Summit Assembly',
    'caption': 'Pan-African leadership gathering in Accra, Ghana, bringing together public servants, innovators, and philanthropists.',
    'category': 'international',
    'date': '2026-04-11',
    'location': 'Accra, Ghana',
    'subjectConfirmed': True,
    'credit': 'Photo: Premium Times',
    'source': 'Premium Times',
    'sourceUrl': 'https://www.premiumtimesng.com/promoted/871209-abdulrahman-haske-adesina-walson-jack-others-bag-african-heritage-awards.html',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },

  # Events
  {
    'id': 'events-yola-ribadu-rally',
    'src': '/images/abdulrahman/events/yola-mahmud-ribadu-rally-2026.jpeg',
    'disk': 'public/images/abdulrahman/events/yola-mahmud-ribadu-rally-2026.jpeg',
    'alt': 'Citizens gathered at Mahmud Ribadu Square Yola',
    'title': 'Adamawa Statewide Civic Rally',
    'caption': 'Civic assembly at Mahmud Ribadu Square, Yola, drawing community groups and youth delegations.',
    'category': 'events',
    'date': '2026-04-25',
    'location': 'Mahmud Ribadu Square, Yola, Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: Premium Times',
    'source': 'Premium Times',
    'sourceUrl': 'https://www.premiumtimesng.com/promoted/874756-yola-agog-as-abdulrahman-haske-finally-declares-for-adamawa-governorship-race.html',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },
  {
    'id': 'events-polo-tournament-finale',
    'src': '/images/abdulrahman/events/yola-international-polo-tournament-2026.webp',
    'disk': 'public/images/abdulrahman/events/yola-international-polo-tournament-2026.webp',
    'alt': 'Yola International Polo Tournament 2026',
    'title': '2026 Yola Polo Tournament Finale',
    'caption': 'Annual tournament finale at Lamido Musdafa Polo Ground, drawing premier equestrian squads from across Nigeria.',
    'category': 'events',
    'date': '2026-08',
    'location': 'Lamido Musdafa Polo Ground, Yola, Adamawa State',
    'subjectConfirmed': True,
    'credit': 'Photo: The Nation Newspaper / Headtopics',
    'source': 'The Nation Newspaper',
    'sourceUrl': 'https://thenationonlineng.net/haske-pledges-exciting-2026-yola-international-polo-tournament/',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  },
  {
    'id': 'events-aha-gala-evening',
    'src': '/images/abdulrahman/events/african-heritage-awards-gala-accra.jpg',
    'disk': 'public/images/abdulrahman/events/african-heritage-awards-gala-accra.jpg',
    'alt': 'African Heritage Awards gala in Accra, Ghana',
    'title': 'AHA Gala Evening, Accra',
    'caption': 'Pan-African leaders, diplomats, and innovators assembled at the African Heritage Awards gala in Accra, Ghana.',
    'category': 'events',
    'date': '2026-04-11',
    'location': 'Accra, Ghana',
    'subjectConfirmed': True,
    'credit': 'Photo: Streamline Feed / African Heritage Awards',
    'source': 'Streamline Feed',
    'sourceUrl': 'https://streamlinefeed.co.ke/news/african-heritage-awards-honor-adesina-haske-leaders-of-change',
    'license': 'Editorial press coverage',
    'status': 'SOURCE CONFIRMED',
    'verified': True,
  }
]

out = []
for item in images_meta:
    w, h = get_wh(item['disk'])
    blur = get_blur(item['disk'])
    entry = {
        'id': item['id'],
        'src': item['src'],
        'width': w,
        'height': h,
        'blurDataURL': blur,
        'alt': item['alt'],
        'title': item['title'],
        'caption': item['caption'],
        'category': item['category'],
        'subjectConfirmed': item['subjectConfirmed'],
        'credit': item['credit'],
        'source': item['source'],
        'license': item['license'],
        'status': item['status'],
        'verified': item['verified']
    }
    if 'date' in item: entry['date'] = item['date']
    if 'location' in item: entry['location'] = item['location']
    if 'photographer' in item: entry['photographer'] = item['photographer']
    if 'sourceUrl' in item: entry['sourceUrl'] = item['sourceUrl']
    if 'licenseUrl' in item: entry['licenseUrl'] = item['licenseUrl']
    if item.get('ogCandidate'): entry['ogCandidate'] = True
    out.append(entry)

with open('scratch/generated_library.json', 'w') as f:
    json.dump(out, f, indent=2)

print(f'Successfully generated metadata and blur hashes for {len(out)} images!')
